import { GetStaticProps } from 'next'
import Head from 'next/head'
import { getProposalsByStage } from '../api/proposals'
import { ProposalsByStage } from '../types'

interface Props {
  proposals: ProposalsByStage
}

export const getStaticProps: GetStaticProps = async () => {
  const proposals = await getProposalsByStage()
  const oneHourInSeconds = 1 * 60 * 60

  return {
    props: { proposals },
    revalidate: oneHourInSeconds
  }
}

export default function Proposals({ proposals }: Props) {
  console.log({ proposals })

  return (
    <>
      <Head>
        <title>EcmaScript Proposals</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Proposals</p>
    </>
  )
}
