import { Fragment, useState } from 'react'
import { GetStaticProps } from 'next'
import dynamic from 'next/dynamic'
import Head from 'next/head'
import { PageContainer, Col, SearchBar } from '../components/common'
import { getProposalsForStages } from '../api/getProposalsForStages'
import { ProposalsByStage, allStages } from '../types'
import { useMediaQuery } from '../hooks/useMediaQuery'
import { ProposalList } from '../components/proposals'
import { formatStageName } from '../utils/formatStageName'
import { GoChevronDown } from 'react-icons/go'
import { Expander } from '../components/common/Expander'

const DynamicStageWithProposals = dynamic(async () => {
  const { StageWithProposals } = await import('../components/stages/StageWithProposals')
  return StageWithProposals
})

interface Props {
  proposals: ProposalsByStage
}

export const getStaticProps: GetStaticProps = async () => {
  const proposals = await getProposalsForStages({
    stages: allStages,
    includeRepoDetails: true
  })

  return {
    props: { proposals },
    revalidate: 1 * 60 * 60 // Revalidate every once per hour
  }
}

export default function ProposalsPage({ proposals }: Props) {
  const [searchQuery, setSearchQuery] = useState('')
  const isMobile = useMediaQuery('(max-width: 768px)')
  const isDesktop = !isMobile && isMobile != null
  console.log({ isMobile })

  return (
    <>
      <Head>
        <title>EcmaScript Proposals</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageContainer
        layout="column"
        gap={isDesktop ? '3rem' : '1.25rem'}
        width="100%"
        mobileWidth="95%"
        margin="0 auto"
      >
        <SearchBar
          searchQuery={searchQuery}
          setSearchQuery={setSearchQuery}
          placeholder="Search for proposals..."
          hideOnMobile
          width="50rem"
        />
        {allStages.map((stage) =>
          isDesktop ? (
            <DynamicStageWithProposals
              key={stage}
              stage={stage}
              proposals={proposals[stage]}
              searchQuery={searchQuery}
            />
          ) : (
            <Col>
              <Expander
                sticky
                heading={formatStageName(stage)}
                icon={<GoChevronDown />}
                searchQuery={searchQuery}
              >
                <ProposalList
                  proposals={proposals[stage]}
                  searchQuery={searchQuery}
                  badges={['stars']}
                />
              </Expander>
            </Col>
          )
        )}
      </PageContainer>
    </>
  )
}
