import { GetServerSideProps } from 'next'
import Head from 'next/head'
import useSWR from 'swr'
import { getProposals } from '../api/github'
import { ProposalsByStage } from '../types'

interface Props {
  proposals: ProposalsByStage
}

const fetcher = (url: string) => fetch(url).then((res) => res.json())

export const getServerSideProps: GetServerSideProps = async () => {
  const proposals = await getProposals()
  return {
    props: {
      proposals
    }
  }
}

export default function Proposals(props: Props) {
  const { data: proposals } = useSWR('/api/proposals', fetcher, {
    initialData: props.proposals
  })

  console.log({ proposals })

  return (
    <>
      <Head>
        <title>EcmaScript Proposals</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}
