import { GetStaticProps } from 'next'
import Head from 'next/head'

export const getStaticProps: GetStaticProps = async () => {
  return {
    props: {}
  }
}

export default function Home() {
  return (
    <>
      <Head>
        <title>EcmaScript Proposals</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}
