import { GetServerSideProps } from 'next'
import Head from 'next/head'
import { getProposals } from '../api/github'

export const getServerSideProps: GetServerSideProps = async () => {
  await getProposals()

  return {
    props: {}
  }
}

export default function Home() {
  return (
    <>
      <Head>
        <title>EcmaScript Proposals</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}
